version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - 5672:5672
      - 15672:15672
#    environment:
#      - RABBITMQ_DEFAULT_USER=guest
#      - RABBITMQ_DEFAULT_PASS=welcome1
#      - RABBITMQ_NODENAME=rabbitnode@localhost
#      - RABBITMQ_USER=skipper
#      - RABBITMQ_PASSWORD=welcome1
